canonical/kratos-operator

- README.md
- integration-requirements.txt
- lib/charms/traefik_k8s/v1/ingress.py
- metadata.yaml
- requirements.txt
- src/charm.py
- tests/integration/test_charm.py
- tests/unit/conftest.py
- tests/unit/test_charm.py
- tox.ini
Add ingress relation.
To test this on a model that has kratos deployed you need to run (we need `channel=latest/edge` due to https://github.com/canonical/traefik-k8s-operator/pull/114):
```console
juju deploy traefik-k8s traefik-public --channel latest/edge
juju deploy traefik-k8s traefik-admin --channel latest/edge
juju config traefik-public external_hostname=some_host
juju config traefik-admin external_hostname=some_host
juju relate traefik-public kratos:public-ingress
juju relate traefik-admin kratos:admin-ingress
```
After all models in the unit reach an active state, get the traefik IPs by running:
```console
juju status
...
traefik-admin/0*                  active       idle   {admin_IP}         
traefik-public/0*                  active       idle   {public_IP}         
```
Then on …
> Add ingress

- src/charm.py
- templates/kratos.yaml.j2
- tests/unit/conftest.py
- tests/unit/test_charm.py
Only run database migration on database created event
Updated unit tests
> rewrite event handlers to only run data migration on database created event

- config.yaml
- src/charm.py
- tests/unit/test_charm.py
Adds configuration option for using the `dev` flag when starting Kratos. This flag is needed when running Kratos without HTTPS
> Add dev flag

- .github/workflows/on_schedule.yaml
- .github/workflows/tests.yaml
- Fix `on_schedule` workflow: update-libs job requires charmcraft secret
- Fix tests workflow: update juju version to 3.1 and point microk8s to strict confinement version (juju 3.1+ requirement)
> Fix workflows

- README.md
- actions.yaml
- requirements.txt
- src/charm.py
- src/identity.admin.schema.json
- src/kratos.py
- templates/kratos.yaml.j2
- tests/integration/test_charm.py
- tests/unit/conftest.py
- tests/unit/test_charm.py
- tests/unit/test_kratos.py
- unit-requirements.txt
> Add actions

- config.yaml
- src/charm.py
- src/utils.py
- tests/unit/test_charm.py
- tests/unit/test_utils.py
- Convert ingress provided URLs to https and remove the port.
- Remove `external_url` config.
>  Convert ingress provided URLs to https

- src/charm.py
- tests/unit/conftest.py
- tests/unit/test_charm.py
Fixed the issue of directory in log file path not being present in rock. Manually verified to work.
To test:
- deploy kratos
- deploy loki
- integrate kratos with loki
- after entering ```curl loki_url:3100/loki/api/v1/label/juju_unit/values``` command you should see the kratos unit you deployed
> fix: fixed issue around the log file directory

- lib/charms/kratos/v0/kratos_endpoints.py
- src/charm.py
- tests/unit/test_charm.py
- adds login browser and sessions endpoints to the `kratos_endpoints` library
- uses ingress (if relation provided) instead of service to communicate with other components, since oathkeeper and kratos can be in different models.
> Add login and sessions endpoints to kratos lib

- lib/charms/grafana_k8s/v0/grafana_dashboard.py
- metadata.yaml
- src/charm.py
- src/grafana_dashboards/kratos.json.tmpl
This commit adds the dashboard to the Kratos operator.
To verify the kratos dashboard, you will need to deploy cos bundle, postgresql and kratos:
```
juju deploy cos-lite --trust
juju deploy postgresql-k8s --trust
```
Pack and deploy kratos operator (in the operator root directory):
```
charmcraft pack
juju deploy ./kratos*.charm  --resource oci-image=$(yq eval '.resources.oci-image.upstream-source' metadata.yaml) --trust
juju integrate kratos postgresql-k8s
```
You need to make the following integrations:
```
juju integrate kratos grafana
```
After this you may access grafana's UI with your browser. The url is grafana-ip:3000. Username is admin, you can get the password with `juju run grafana/0 get-admin-password`
On the grafana interface you should be able to find the dashboards in the …
> IAM-210-Add dashboard to Kratos Operator

- lib/charms/tempo_k8s/v0/tracing.py
- metadata.yaml
- src/charm.py
- tests/unit/test_charm.py
This pr updates the tracing integration to the Kratos Operator.
---
Testing:
The tracing configurations for kratos are in envars.
A unit test is in there to make sure that the correct pebble layer gets rendered after relation with tempo.
You will need to deploy tempo-k8s, kratos operator, postgresql-k8s, grafana-k8s to verify the that tracing is working.
Integrate kratos with the data backend, then with tempo-k8s.
```
juju integrate kratos tempo-k8s
```
Integrate tempo-k8s with grafana as a grafana source:
```
juju integrate tempo-k8s grafana-k8s:grafana-source
```
Open grafana in the browser: grafana_ip:3000
login name: admin
to get password run:
```
juju run grafana-k8s/0 get-admin-password
```
Go to the explore button in the menu. Pick tempo as the data source. Set the query type to …
> IAM-395 Update Tracing relation

- CONTRIBUTING.md
- src/charm.py
- src/utils.py
- tests/integration/test_charm.py
This pull request aims to provide public endpoints with HTTP protocol in the `kratos-endpoint-info` integration.
**Note:** pls ignore the changes in the CONTRIBUTING.md. It's just formatting changes.
> fix: use http endpoint in kratos-endpoint-info integration

- .github/workflows/auto-approver.yaml
The approver bot will now enable auto merge is required. For some reason the renovate PRs didn't have it turned on even if enabled.
> Fix automerge

- src/charm.py
- src/kratos.py
- tests/unit/conftest.py
- tests/unit/test_charm.py
- tests/unit/test_kratos.py
Improvements around the migration logic. The goal is to bring the Kratos charm closer to the logic in the Hydra charm.
Changes:
- JSON dump the contents in the peer relation, this will make backwards compatibility much easier to achieve. Currently the charm stores the migration version in the peer relation as a string: `{"db_migrate_version": "0.11.1"}`, after these changes the version will be json dumped: `{"db_migrate_version": '"0.11.1"'}`. This is a breaking change and will cause the charm to go to an error state if you try to upgrade from the previous version to this.
- Use DSN from env var to run migration instead of having to read the config file. This will make it much simpler to run the migrations once the configMap is introduced (we won't have to wait for the configMap to update …
> Improve migration logic

- src/grafana_dashboards/kratos.json.tmpl
- src/loki_alert_rules/kratos_high_severity_log.rule
- src/prometheus_alert_rules/kratos_unavailable.rule
IAM-486
IAM-488
Updates the grafana dashboards:
These changes were based on https://github.com/canonical/hydra-operator/pull/90#discussion_r1263706081. Couldn't remove the unused variables.
Updates the alert rules
> Update dashboards and alert rules

- src/charm.py
- tests/unit/test_charm.py
When the public ingress is available, its url is added to the allowed return urls in Kratos' config file.
If the url of the public ingress is http://ingress:80/path/subpath it gets added to the config file as https://ingress/*.
> Add public ingress url to allowed return urls

- .github/workflows/update_libs.yaml
Enabling the auto-merge option in the create-pull-request action tried to squash the commits, which is not allowed by our repo config.
> Fix on_schedule workflow

- requirements.txt
- src/loki_alert_rules/kratos_high_severity_log.rule
- tests/unit/test_charm.py
This PR simply adds a LogQL `label filter` to avoid loki processing log entry that failed json parsing.
This PR also fixes unit tests that failed due to breaking changes in new `ops` dependency.
Main dependencies are pinned now.
> fix(loki-rule): improve error handling in json parsing

- lib/charms/harness_extensions/v0/capture_events.py
- lib/charms/kratos/v0/kratos_endpoints.py
- lib/charms/kratos/v0/kratos_info.py
- metadata.yaml
- pyproject.toml
- src/charm.py
- tests/unit/capture_events.py
- tests/unit/conftest.py
- tests/unit/test_charm.py
This PR adds a new `kratos-info` interface providing endpoints and configmaps details in a single relation.
It deprecates the `kratos-endpoint-info` interface which has a narrow scope.
> Add `kratos-info` interface

- lib/charms/traefik_route_k8s/v0/traefik_route.py
- metadata.yaml
- requirements.txt
- src/charm.py
- src/constants.py
- src/utils.py
- tests/integration/test_charm.py
- tests/unit/test_charm.py
IAM-942: introduce internal-ingress via `traefik-route`
- **feat: introduce internal ingress**
- **fix: use internal ingress if set, otherwise stick with k8s networking**
> IAM-942: internal ingress support

- .github/workflows/tests.yaml
- README.md
- charmcraft.yaml
- requirements.txt
- src/charm.py
- src/kratos.py
- tests/integration/test_charm.py
- tests/unit/conftest.py
- tests/unit/test_charm.py
- tests/unit/test_kratos.py
This PR adds juju actions for sessions invalidation, password reset (with either recovery code or a password hashed with the default bcrypt algorithm) and mfa credentials reset.
It removes password reset with link method because it is [considered deprecated](https://www.ory.sh/docs/kratos/self-service/flows/account-recovery-password-reset#comparison).
Password will still be required for admin account creation because the credentials must be provided in `kratos import identities`.
> feat: add account management actions

- charmcraft.yaml
- identity_schemas/admin_v0.json
- identity_schemas/social_user_v0.json
- lib/charms/identity_platform_login_ui_operator/v0/login_ui_endpoints.py
- src/charm.py
- templates/kratos.yaml.j2
- tests/unit/test_charm.py
This PR adds support for local identity provider:
- updates identity schemas with email identifiers for the new flow methods
- adds config options to enable Kratos IdP and passwordless login method
- updates the config template
- bumps `ui-endpoint-info` lib
1. Build kratos with `charmcraft pack`.
2. Render and deploy the identity platform bundle, replacing kratos with the locally built charm and bumping login ui revision (105 or higher).
`juju deploy ./bundle-edge.yaml --trust`
3. Deploy grafana with required relations:
```
juju deploy grafana-k8s
juju integrate grafana-k8s:ingress traefik-public
juju integrate grafana-k8s:oauth hydra
```
4. Create a user in kratos:
`juju run kratos/0 create-admin-account email=test@example.com password=test username=admin`
5. Go to …
> feat: support local identity provider

- charmcraft.yaml
- lib/charms/kratos/v0/kratos_info.py
- src/charm.py
- templates/kratos.yaml.j2
- tests/unit/test_charm.py
This PR adds a config option to enable/disable MFA and updates the `kratos-info` interface to include the flag (this will be required by login-ui).
> Add `enforce_mfa` config option

- lib/charms/kratos/v0/kratos_info.py
- pyproject.toml
- src/charm.py
- src/constants.py
- tests/integration/test_charm.py
- tests/unit/test_charm.py
IAM-1066: addressing redirection issue for oathkeeper charm
closes #267
> fix: use [external] ingress on login endpoint field of kratos info

- charmcraft.yaml
- lib/charms/kratos/v0/kratos_info.py
- src/charm.py
- templates/kratos.yaml.j2
- tests/unit/test_charm.py
This PR adds support for authentication factors sequencing:
- updates the `reset-identity-mfa` action to include `webauthn`
- adds a config option `enable_oidc_webauthn_sequencing`
- updates the kratos config template
- updates the `kratos-info` lib to include the mode - adds `oidc_webauthn_sequencing_enabled` to relation data.
> feat: support oidc webauthn sequencing mode

- lib/charms/identity_platform_login_ui_operator/v0/login_ui_endpoints.py
- src/charm.py
- templates/kratos.yaml.j2
- tests/unit/test_charm.py
This PR changes the default return url for webauthn method, so that the user remains on the setup page after removing or adding a key. This will not influence any redirect when setup is enforced during login.
fixes https://github.com/canonical/identity-platform-login-ui/issues/381
> Set a default return url for webauthn settings

- charmcraft.yaml
fix CVE-2024-6345
fix CVE-2022-40897
closes #372
```
shipperizer in ~/shipperizer/kratos-operator on ci/identity ● λ secscan-client --batch submit --scanner trivy --type package --format charm ./*ubuntu@22.04-amd64.charm --wait-and-print
Scan request submitted.
Scan request is running.
Scan has succeeded.
Scan request information:
Started at:        2025-04-01 07:50:40+00:00
Completed at:      2025-04-01 07:50:48+00:00
Scanner:           trivy
Target:            s3://secscan-attachments/edfa447e-62f3-4521-b311-abb8f7791a6f
Target type:       package
Target format:     charm
Target vulnerabilities:
```
> IAM-1408: address charm CVEs with setupttools

- templates/kratos.yaml.j2
- tests/unit/test_charm.py
As discovered in https://warthogs.atlassian.net/browse/IAM-1436, the `profile` method is enabled by default, in contrast to what the kratos configuration [reference](https://www.ory.sh/docs/kratos/reference/configuration) states.
After an internal discussion we agreed to disable the method since we don't support profile changes in the UI (and kratos actions use the admin API). Along with `profile` we also disable `passkey` and magic `link` as those methods are not supported either.
> fix: explicitly disable unsupported methods

- src/constants.py
This pull request aims to fix the idp k8s configmap key name to align with admin ui. The value should be a JSON string. Related to https://github.com/canonical/identity-platform-admin-ui/pull/588
> fix: align the idp k8s configmap key name
