canonical/kratos-operator

README.md
config.yaml
src/charm.py
tests/unit/test_charm.py

expose smtp connection uri as a config

add smtp config

---

lib/charms/kratos/v0/kratos_endpoints.py

All units must be able to get the kratos endpoints.

Allow non-leader units to get endpoints

---

lib/charms/kratos/v0/kratos_endpoints.py
pyproject.toml
src/charm.py
tests/integration/test_charm.py
tests/unit/__init__.py
tests/unit/conftest.py
tests/unit/test_charm.py
tests/unit/test_kratos.py

Add mypy configuration to `pyproject.toml` and fix any type errors that existed (where it made sense)

Add type hints

---

src/charm.py
tests/integration/test_charm.py
tests/unit/test_charm.py

There is no reason to use the ingress since all of our components will be in the same k8s cluster, in the same model.

Use service to communicate with other components

---

.github/workflows/tests.yaml
metadata.yaml

Switch metadata image to canonical ROCK

Use ROCK image

---

claim_mappers/microsoft_schema.jsonnet
tests/integration/test_charm.py

Add Microsoft jsonnet

---

lib/charms/kratos_external_idp_integrator/v0/kratos_external_provider.py
templates/kratos.yaml.j2
tests/unit/test_charm.py

Adds support for user defined scope, provider_id and jsonnet_mapper.

Update external idp library

---

src/charm.py
tests/integration/test_charm.py
tests/unit/test_charm.py

Push files to container on install, this makes sure that they will be pushed before any hook that tries to run the service.
Closes #74

Push files to container on install

---

src/charm.py
templates/kratos.yaml.j2
tests/unit/test_charm.py

Redirect the user to the login UI after login in to bypass Kratos bug.

Add allowed_return_urls

---

.github/workflows/tests.yaml
src/charm.py
templates/kratos.yaml.j2
tests/unit/test_charm.py

Generate cookie secret and store it in juju secrets.
Closes #82

Fix cookie secret sharing

---

src/charm.py
src/kratos.py
tests/unit/test_charm.py
tests/unit/test_kratos.py

This pull request attempts to fix the https://github.com/canonical/kratos-operator/issues/101.

fix: fix the run-migration action failing condition issue

---

src/grafana_dashboards/kratos.json.tmpl

Fixed the bug that prevented the dashboard from showing up in the Grafana's browser UI.

Dashboard fix

---

lib/charms/hydra/v0/hydra_endpoints.py
metadata.yaml
src/charm.py
tests/unit/test_charm.py

Changed hydra relation name from endpoint-info to hydra-endpoint-info, and updated hydra_endpoints lib.

Updated hydra_endpoints relation name

---

lib/charms/identity_platform_login_ui_operator/v0/login_ui_endpoints.py
tests/unit/test_charm.py

Updated to latest login_ui_endpoints charm lib, and updated associated unit tests.

login_ui_endpoints relation and unit test update

---

lib/charms/traefik_k8s/v2/ingress.py
src/charm.py
tests/unit/test_charm.py

IAM-422:
- Migrate ingress to v2

Migrate to ingress v2

---

.github/workflows/renovate.yaml
renovate.json

- fix: add token
- fix: use RENOVATE_TOKEN env var
- fix: add automerge enabled

IAM 414 fix automerge

---

lib/charms/data_platform_libs/v0/data_interfaces.py
lib/charms/grafana_k8s/v0/grafana_dashboard.py
lib/charms/loki_k8s/v0/loki_push_api.py
lib/charms/prometheus_k8s/v0/prometheus_scrape.py
lib/charms/traefik_k8s/v2/ingress.py
requirements.txt

(Automated) Update Charm Libs

---

templates/kratos.yaml.j2
tests/unit/test_charm.py

Fix invalid config when no OIDC Provider

---

src/charm.py
tests/integration/test_charm.py
tests/unit/test_charm.py

Fix database logic

---

requirements.txt
src/charm.py
tests/unit/test_charm.py

Remove `*` from allowed_urls

---

lib/charms/kratos_external_idp_integrator/v0/kratos_external_provider.py
src/charm.py
tests/unit/test_charm.py

Update kratos_external_idp_integrator lib and properly handle provider removal.

Update kratos_external_idp_integrator lib

---

metadata.yaml
src/charm.py
src/kratos.py
tests/unit/test_kratos.py

To avoid https://github.com/canonical/identity-platform-login-ui/issues/238

Downgrade Kratos

---

metadata.yaml
src/charm.py
src/kratos.py
tests/unit/test_kratos.py

Bump kratos img to 1.1.0

---

lib/charms/certificate_transfer_interface/v0/certificate_transfer.py
metadata.yaml
src/certificate_transfer_integration.py
src/charm.py
src/constants.py
tests/unit/conftest.py

Add cert transfer integration, do not require the workload image to trust the public CAs
Closes #194

Cert transfer integration

---

requirements.txt

Unpin macaroonbakery

---

README.md
charmcraft.yaml
lib/charms/smtp_integrator/v0/smtp.py
src/charm.py
templates/kratos.yaml.j2
tests/unit/conftest.py
tests/unit/test_charm.py

This PR adds `smtp` integration.

SMTP integration

---

src/certificate_transfer_integration.py
src/charm.py
src/constants.py
src/kratos.py
tests/integration/test_charm.py
tests/unit/conftest.py
tests/unit/test_charm.py
tests/unit/test_kratos.py

Move charm constants to separate file

---

src/charm.py
src/utils.py
tests/unit/conftest.py
tests/unit/test_utils.py

Wait for configmap changes to apply

---

templates/kratos.yaml.j2
tests/unit/test_charm.py

This PR adds support for lookup secrets (backup codes).

feat: support backup codes if mfa enabled

---

lib/charms/kratos_external_idp_integrator/v0/kratos_external_provider.py
src/charm.py
src/constants.py

IAM-1019
Need to merge https://github.com/canonical/kratos-external-idp-integrator/pull/125 first

Fix integration with admin UI

---

README.md
tests/integration/test_charm.py

fixes https://github.com/canonical/kratos-operator/issues/269

tests: enable `pg_trgm` and `btree_gin` postgres plugins

---

src/charm.py

in `src/charm.py` on line 1177

Fix a small typo 

---

.github/workflows/publish.yaml

following https://github.com/canonical/kratos-operator/pull/294
fixes https://github.com/canonical/kratos-operator/issues/295

ci: build charm with disabled destructive mode

---

.github/workflows/_deploy.yaml
.github/workflows/on_push.yaml
.github/workflows/publish.yaml
.github/workflows/release.yaml
deployment/main.tf

deploying to our environments using GH actions and JIMM
https://github.com/canonical/kratos-operator/actions/workflows/publish.yaml

ci: add remote deployment

---

deployment/common.auto.tfvars

enable AAL in dev and staging deployments

ci: enable aal in kratos

---

charmcraft.yaml

Set relation optional flag to True for optional relations
See https://canonical-charmcraft.readthedocs-hosted.com/en/stable/reference/files/metadata-yaml-file/#heading--requires for more information.

set optional flag true for optional relations

---

pyproject.toml

Fix the lint ci due to the ruff upgrade.

fix: fix the lint ci

---

.github/workflows/ci.yaml
.github/workflows/publish.yaml
tests/integration/conftest.py
tests/integration/test_charm.py
tox.ini

- **ci: use reusable workflows with charmcraftcache**
- **ci: reuse prebuilt charm during int tests**

IAM-1362: use reusable workflows for tests

---

src/charm.py

This pull request tries to resolve the https://github.com/canonical/kratos-operator/issues/380.

fix: fix the statefulset's name

---

.gitignore
lib/charms/kratos/v0/kratos_registration_webhook.py
templates/kratos.yaml.j2

Add API auth to webhook

---

lib/charms/data_platform_libs/v0/data_interfaces.py
lib/charms/grafana_k8s/v0/grafana_dashboard.py
lib/charms/prometheus_k8s/v0/prometheus_scrape.py
lib/charms/tempo_coordinator_k8s/v0/tracing.py

Update charm dependent libraries

(Automated) Update Charm Dependent Libs

---

deployment/common.auto.tfvars

As discussed, I am scaling up our dev/stg envs to make it more closely mimic production use deployments

Scale up dev/stg units

---

lib/charms/kratos_external_idp_integrator/v0/kratos_external_provider.py

This pull request aims to update the kratos external provider library.

chore: update kratos external provider library

---

.github/workflows/publish.yaml
deployment/common.auto.tfvars
deployment/main.tf
terraform/MODULE_SPECS.md
terraform/main.tf
terraform/outputs.tf
terraform/versions.tf

- **feat: update juju_application resource name**
- **fix: use terraform module in deployment**
- **ci: update params for deployment wf**

IAM-1572: use tf module in gh deployments
